import Image from "next/image";
import Link from "next/link";
import type { ProductLineEntry } from "../catalog-lines";

export function ProductLinePage({ line }: { line: ProductLineEntry }) {
  const modelCount = line.ranges.reduce((sum, item) => sum + item.modelCount, 0);
  const schema = { "@context": "https://schema.org", "@type": "CollectionPage", name: `${line.nameVi} Rotork`, url: `https://rotork.com.vn/san-pham/${line.slug}`, mainEntity: { "@type": "ItemList", itemListElement: line.ranges.map((item, index) => ({ "@type": "ListItem", position: index + 1, name: item.name, url: `https://rotork.com.vn/san-pham/${line.slug}/${item.slug}` })) } };
  return <main id="main">
    <section className="range-hero product-line-hero"><div className="container"><nav className="deep-breadcrumb" aria-label="Breadcrumb"><Link href="/">Trang chủ</Link><span>›</span><Link href="/san-pham">Sản phẩm</Link><span>›</span><strong>{line.nameVi}</strong></nav><div className="range-hero-grid"><div><span className="kicker light">ROTORK PRODUCT GROUP</span><h1>{line.nameVi}</h1><p>{line.description}</p><div className="range-actions"><Link className="button button-red" href="#range-trong-nhom">Xem các range <span>↓</span></Link><Link className="button button-outline-light" href={`/lien-he?model=${encodeURIComponent(line.name)}`}>Yêu cầu tư vấn</Link></div></div><div className="range-hero-visual"><div className="range-image-circle"/><Image src={line.ranges[0].image} alt={`${line.nameVi} Rotork`} width={700} height={700} priority/><span>{line.ranges.length} ranges<br/>{modelCount} models</span></div></div></div></section>
    <section className="range-facts"><div className="container"><div><strong>{line.ranges.length}</strong><span>Range sản phẩm</span></div><div><strong>{modelCount}</strong><span>Model/cấu hình READY</span></div><div><strong>Official</strong><span>Nguồn dữ liệu Rotork</span></div><div><strong>SEO</strong><span>URL riêng cho range và model</span></div></div></section>
    <section className="section section-gray" id="range-trong-nhom"><div className="container"><div className="section-head split-head"><div><span className="kicker">RANGE TRONG NHÓM</span><h2>Chọn dòng sản phẩm cần tra cứu</h2></div><p>Mỗi range có trang tổng quan, bộ lọc model, tài liệu nguồn và liên kết yêu cầu báo giá.</p></div><div className="line-range-grid">{line.ranges.map((item) => <Link href={`/san-pham/${line.slug}/${item.slug}`} className="line-range-card" key={item.slug}><div><Image src={item.image} alt={`${item.name} Rotork`} width={560} height={420}/></div><span>{item.modelCount} model/cấu hình</span><h2>{item.name}</h2><p>{item.description}</p><strong>Xem range →</strong></Link>)}</div></div></section>
    <section className="product-final-cta"><div className="container"><div><span>{line.name.toUpperCase()}</span><h2>Chưa xác định được range hoặc model?</h2><p>Gửi ảnh nameplate, BOM, valve data hoặc yêu cầu kỹ thuật cho Fast Group Engineering.</p></div><Link className="button button-white" href="/lien-he">Gửi yêu cầu tra cứu →</Link></div></section>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}/>
  </main>;
}
