import type { CatalogModel, RangeConfig } from "./catalog-types";

const precisionCategory = "Precision Modulating Actuators";
const precisionSlug = "precision-modulating-actuators";
const hydraulicCategory = "Electro-Hydraulic Actuators";
const hydraulicSlug = "electro-hydraulic-actuators";

export const cmaConfig: RangeConfig = {
  slug: "cma", name: "CMA", categoryName: precisionCategory, categorySlug: precisionSlug,
  description: "Dòng actuator all-electric compact cho continuous modulation với độ chính xác vị trí tới 0,1%, gồm đầu ra linear, part-turn và multi-turn.", heroBadge: "Compact precision\nmodulation",
  facts: [["0,1%", "Độ chính xác tới mức công bố"], ["3 output types", "Linear · Part-turn · Multi-turn"], ["<1 W", "Standby power"], ["RPP option", "Fail-to-position bằng supercapacitor"]],
  overviewTitle: "Điều khiển chính xác trong thiết kế all-electric compact", overview: ["CMA sử dụng brushless DC motor, encoder contactless và giao diện cài đặt tích hợp cho control valve và pump applications.", "Các model hỗ trợ 4–20 mA, fieldbus, hardwired hoặc analogue systems. Explosionproof, local controls và Reserve Power Pack phụ thuộc cấu hình."],
  selectionTitle: "Chọn đầu ra trước, sau đó xác định lực hoặc torque", selectionIntro: "CML cho linear output, CMQ cho part-turn và CMR cho multi-turn. Cấu hình tiếp theo dựa trên seating load, modulating load, stroke, speed và giao thức.",
  selectionSteps: [["Linear, part-turn hay multi-turn?", "Xác định chuyển động và kiểu ghép nối với control valve hoặc pump."], ["Load và tốc độ?", "Đối chiếu seating thrust/torque, modulating load, stroke và thời gian đáp ứng."], ["Control và fail position?", "Xác nhận 4–20 mA, fieldbus, local controls, RPP và hazardous-area certification."]],
  commonFeatures: [["Brushless DC motor", "Cung cấp continuous modulation chính xác và tin cậy."], ["Contactless encoder", "Feedback vị trí không tiếp xúc cho khả năng lặp lại cao."], ["Low standby power", "Mức standby dưới 1 W theo mô tả range."], ["Flexible integration", "Hỗ trợ nhiều hệ thống fieldbus, hardwired và analogue."]],
  brochureCode: "PUB094-001", brochureTitle: "CMA Range Publication", brochureUrl: "https://media.rotork.com/api/public/content/pub094-001-000912-pdf-rtkimportasseta74a44.pdf", officialRangeUrl: "https://www.rotork.com/en/products/precision-modulating-actuators/cma",
};

export const cmaModels: CatalogModel[] = [
  { slug: "cml", name: "CML", type: "Linear", duty: "Continuous modulation", image: "/images/products/cma/cml.jpg", summary: "Actuator linear compact với seating thrust tới 20.017 N và position control tới 0,1%.", description: "CML là giải pháp all-electric cho control valve và pump, có adjustable speed, electronic thrust limiting và tùy chọn Reserve Power Pack.", highlights: ["Seating thrust tới 20.017 N", "Accuracy tới 0,1%", "1 pha hoặc DC", "Explosionproof option"], specs: [["Đầu ra", "Linear"], ["Seating thrust", "Tới 20.017 N"], ["Control signal", "4–20 mA"], ["Accuracy", "Tới 0,1%"], ["Nhiệt độ tiêu chuẩn", "-30 đến 70 °C"], ["Nguồn", "1 pha hoặc DC"]], officialUrl: "https://www.rotork.com/en/products/precision-modulating-actuators/cma/cml" },
  { slug: "cml-15003000", name: "CML-1500/3000", type: "Linear high-thrust", duty: "Continuous modulation", image: "/images/products/cma/cml-15003000.jpg", summary: "Actuator linear cho control valve lớn, seating thrust tới 20 kN, modulating thrust tới 13,3 kN và stroke 114,3 mm.", description: "CML-1500/3000 sử dụng enclosed ball screw drive train để tăng độ tin cậy và hiệu suất ở tải cao.", highlights: ["Seating thrust 20 kN", "Modulating thrust 13,3 kN", "Stroke 114,3 mm", "Accuracy tới 0,1%"], specs: [["Đầu ra", "Linear"], ["Seating thrust", "Tới 20 kN"], ["Modulating thrust", "Tới 13,3 kN"], ["Stroke", "114,3 mm"], ["Control signal", "4–20 mA"], ["Accuracy", "Tới 0,1%"]], officialUrl: "https://www.rotork.com/en/products/precision-modulating-actuators/cma/cml-15003000" },
  { slug: "cmq", name: "CMQ", type: "Part-turn", duty: "Continuous modulation", image: "/images/products/cma/cmq.jpg", summary: "Actuator part-turn compact với seating torque tới 124 Nm và position control tới 0,1%.", description: "CMQ là giải pháp quarter-turn all-electric cho control valve và pump, có adjustable speed, torque limiting và RPP tùy chọn.", highlights: ["Seating torque tới 124 Nm", "Accuracy tới 0,1%", "Part-turn output", "RPP option"], specs: [["Đầu ra", "Part-turn"], ["Seating torque", "Tới 124 Nm"], ["Control signal", "4–20 mA"], ["Accuracy", "Tới 0,1%"], ["Nguồn", "1 pha hoặc DC"], ["Standby", "Dưới 1 W"]], officialUrl: "https://www.rotork.com/en/products/precision-modulating-actuators/cma/cmq" },
  { slug: "cmr", name: "CMR", type: "Multi-turn", duty: "Continuous modulation", image: "/images/products/cma/cmr.jpg", summary: "Actuator multi-turn compact với rated torque tới 45 Nm cho continuous modulation chính xác.", description: "CMR cung cấp đầu ra multi-turn all-electric; cấu hình CMR-250 kết hợp GBX có thể tạo giải pháp part-turn torque cao.", highlights: ["Rated torque tới 45 Nm", "Accuracy tới 0,1%", "Multi-turn output", "Fieldbus options"], specs: [["Đầu ra", "Multi-turn"], ["Rated torque", "Tới 45 Nm"], ["Control signal", "4–20 mA"], ["Accuracy", "Tới 0,1%"], ["Nguồn", "1 pha hoặc DC"], ["Standby", "Dưới 1 W"]], officialUrl: "https://www.rotork.com/en/products/precision-modulating-actuators/cma/cmr" },
];

export const cvaConfig: RangeConfig = {
  slug: "cva", name: "CVA", categoryName: precisionCategory, categorySlug: precisionSlug,
  description: "Actuator điện process control cho continuous unrestricted modulation S9, có phiên bản linear và part-turn, enclosure IP68 và explosionproof.", heroBadge: "Continuous S9\nprocess control",
  facts: [["S9", "Continuous unrestricted modulation"], ["IP68", "Double-sealed enclosure"], ["4–20 mA", "Accurate positional control"], ["Supercapacitor", "Fail-to-position option"]],
  overviewTitle: "Precision control với năng lượng tiêu thụ thấp", overview: ["CVA phù hợp control valve tại vị trí remote, kể cả ứng dụng solar-powered, nhờ mức tiêu thụ năng lượng rất thấp.", "Range hỗ trợ Bluetooth setup, data logger, nhiều giao thức số và tùy chọn intrinsically safe I/O."],
  selectionTitle: "Chọn CVL cho linear hoặc CVQ cho part-turn", selectionIntro: "Cần xác định output movement, thrust/torque, duty S9, power supply, fail position và communication protocol.",
  selectionSteps: [["Linear hay part-turn?", "CVL cho linear control valve; CVQ cho quarter-turn control valve."], ["Nguồn và fail position?", "Xác nhận 1 pha/DC và supercapacitor fail-to-position."], ["Kết nối và hazardous area?", "Chọn HART, Foundation Fieldbus, Profibus, Pakscan, Modbus, RIRO và chứng nhận."]],
  commonFeatures: [["S9 modulation", "Continuous unrestricted modulation cho process control."], ["Double-sealed IP68", "Bảo vệ enclosure trong môi trường khắt khe."], ["Bluetooth setup", "Cài đặt, điều khiển và diagnostic tại chỗ."], ["Direct load measurement", "Đo thrust hoặc torque trực tiếp để bảo vệ và giám sát."]],
  brochureCode: "PUB042-001", brochureTitle: "CVA Range Publication", brochureUrl: "https://media.rotork.com/api/public/content/pub042-001-000512-pdf-rtkimportasset8b4f53.pdf", officialRangeUrl: "https://www.rotork.com/en/products/precision-modulating-actuators/cva",
};

export const cvaModels: CatalogModel[] = [
  { slug: "cvl", name: "CVL", type: "Linear", duty: "S9 continuous modulation", image: "/images/products/cva/cvl.jpg", summary: "Actuator linear process control cho continuous unrestricted modulation, enclosure IP68 và explosionproof.", description: "CVL hỗ trợ 1 pha hoặc DC theo model, data logger, Bluetooth, 4–20 mA và nhiều giao thức fieldbus.", highlights: ["Linear output", "S9 duty", "IP68 / Explosionproof", "Fail-to-position option"], specs: [["Đầu ra", "Linear"], ["Duty", "S9 continuous modulation"], ["Nguồn", "1 pha hoặc DC"], ["Control", "4–20 mA"], ["Enclosure", "IP68 · Explosionproof"], ["Feedback", "Direct thrust measurement"]], officialUrl: "https://www.rotork.com/en/products/precision-modulating-actuators/cva/cvl" },
  { slug: "cvq", name: "CVQ", type: "Part-turn", duty: "S9 continuous modulation", image: "/images/products/cva/cvq.jpg", summary: "Actuator part-turn process control cho continuous unrestricted modulation, enclosure IP68 và explosionproof.", description: "CVQ hỗ trợ 1 pha hoặc DC, direct torque measurement, data logger, Bluetooth và fail-to-position bằng supercapacitor tùy chọn.", highlights: ["Part-turn output", "S9 duty", "Direct torque measurement", "Fail-to-position option"], specs: [["Đầu ra", "Part-turn"], ["Duty", "S9 continuous modulation"], ["Nguồn", "1 pha hoặc DC"], ["Control", "4–20 mA"], ["Enclosure", "IP68 · Explosionproof"], ["Feedback", "Direct torque measurement"]], officialUrl: "https://www.rotork.com/en/products/precision-modulating-actuators/cva/cvq" },
];

export const laConfig: RangeConfig = {
  slug: "la-2000", name: "LA-2000", categoryName: precisionCategory, categorySlug: precisionSlug,
  description: "Dòng actuator linear self-contained cho damper, combustion control, gate, diverter và các ứng dụng positioning công nghiệp.", heroBadge: "Reliable linear\npositioning",
  facts: [["Tới 7.117 N", "Thrust theo model"], ["2.000 starts/h", "Một số cấu hình modulating"], ["AC / DC", "Tùy model"], ["Self-locking", "Hold-in-last position"]],
  overviewTitle: "Linear positioning cho damper và process equipment", overview: ["LA-2000 có drive system self-locking, automatic thrust limiting và manual override tiêu chuẩn.", "Dòng sản phẩm phù hợp các ứng dụng cần positioning tin cậy với housing aluminium chống ăn mòn và khả năng lắp nhiều orientation."],
  selectionTitle: "Chọn theo thrust, nguồn và modulating duty", selectionIntro: "LA-2400 và LA-2500 khác nhau về thrust và power options; cấu hình cụ thể cần đối chiếu hành trình và duty.",
  selectionSteps: [["Thrust yêu cầu?", "Đối chiếu tải positioning và margin với 6.672 N hoặc 7.117 N."], ["Nguồn điện?", "LA-2400 hỗ trợ AC/DC; LA-2500 sử dụng AC theo mô tả range."], ["Duty và communication?", "Xác nhận starts/hour, HART, thrust limiting và manual override."]],
  commonFeatures: [["Self-locking drive", "Giữ vị trí và hạn chế backdriving tới thrust rating."], ["Thrust protection", "Automatic và mechanical thrust overload protection."], ["Manual override", "Trang bị tiêu chuẩn cho vận hành tại chỗ."], ["Flexible mounting", "Grease-lubricated để lắp theo nhiều orientation."]],
  brochureCode: "PUB045-002", brochureTitle: "LA-2000 Range Publication", brochureUrl: "https://media.rotork.com/api/public/content/pub045-002-000212-pdf-rtkimportassetcff06e.pdf", officialRangeUrl: "https://www.rotork.com/en/products/precision-modulating-actuators/la-2000",
};

export const laModels: CatalogModel[] = [
  { slug: "la-2400", name: "LA-2400", type: "Linear", duty: "Positioning / Modulating", image: "/images/products/la-2000/la-2400.jpg", summary: "Actuator linear AC/DC với thrust tới 6.672 N; một số model hỗ trợ modulating tới 2.000 starts/giờ.", description: "LA-2400 phù hợp damper, combustion control, gate, diverter và hydraulic variable speed drive.", highlights: ["Thrust tới 6.672 N", "AC hoặc DC", "Tới 2.000 starts/giờ", "Self-locking drive"], specs: [["Đầu ra", "Linear"], ["Thrust", "Tới 6.672 N"], ["Nguồn", "1 pha · 3 pha · DC"], ["Modulating duty", "Tới 2.000 starts/giờ theo model"], ["Communication", "HART option"], ["Override", "Manual tiêu chuẩn"]], officialUrl: "https://www.rotork.com/en/products/precision-modulating-actuators/la-2000/la-2400" },
  { slug: "la-2500", name: "LA-2500", type: "Linear", duty: "Positioning / Modulating", image: "/images/products/la-2000/la-2500.jpg", summary: "Actuator linear AC với thrust tới 7.117 N; một số model hỗ trợ modulating tới 2.000 starts/giờ.", description: "LA-2500 là actuator self-contained cho positioning damper, gate, diverter và process equipment.", highlights: ["Thrust tới 7.117 N", "Nguồn AC", "Tới 2.000 starts/giờ", "Automatic thrust limiting"], specs: [["Đầu ra", "Linear"], ["Thrust", "Tới 7.117 N"], ["Nguồn", "1 pha hoặc 3 pha"], ["Modulating duty", "Tới 2.000 starts/giờ theo model"], ["Communication", "HART option"], ["Override", "Manual tiêu chuẩn"]], officialUrl: "https://www.rotork.com/en/products/precision-modulating-actuators/la-2000/la-2500" },
];

export const smConfig: RangeConfig = {
  slug: "sm", name: "SM", categoryName: precisionCategory, categorySlug: precisionSlug,
  description: "Actuator internally geared cho damper, vane, valve và process control applications cần high torque và positioning chính xác.", heroBadge: "High-torque\nmodulating control",
  facts: [["Tới 35.251 Nm", "Torque theo model"], ["Continuous", "Modulating duty"], ["Self-locking", "Hold-in-last position"], ["Fieldbus", "Nhiều tùy chọn kết nối"]],
  overviewTitle: "High-torque positioning cho process control", overview: ["SM kết hợp automatic torque limiting, self-locking drive và manual override cho các ứng dụng damper, vane và valve.", "SM-1700/5000 hỗ trợ tới 2.000 starts mỗi giờ; SM-6000 cung cấp continuous unrestricted modulation và torque cao hơn."],
  selectionTitle: "Chọn torque, rotation và duty", selectionIntro: "Cần xác định torque required, góc quay, starts per hour, power supply và communication option.",
  selectionSteps: [["Torque yêu cầu?", "Chọn tới 16.950 Nm hoặc 35.251 Nm theo range."], ["Góc quay?", "Đối chiếu rotation range của SM-1700, SM-5000 hoặc SM-6000."], ["Control và nguồn?", "Xác nhận duty, 1/3 pha hoặc DC, HART, Profibus và Foundation Fieldbus."]],
  commonFeatures: [["Self-locking drive", "Giữ vị trí và hạn chế backdriving."], ["Torque limiting", "Automatic torque limiting bảo vệ drivetrain và thiết bị."], ["Manual override", "Vận hành bằng tay theo cấu hình tiêu chuẩn."], ["Process positioning", "Thiết kế cho damper, vane, valve và process control."]],
  brochureCode: "PUB050-001", brochureTitle: "SM Range Publication", brochureUrl: "https://media.rotork.com/api/public/content/pub050-001-000112-pdf-rtkimportassetc08fc1.pdf", officialRangeUrl: "https://www.rotork.com/en/products/precision-modulating-actuators/sm",
};

export const smModels: CatalogModel[] = [
  { slug: "sm-1700sm-5000", name: "SM-1700/SM-5000", type: "Part-turn geared", duty: "Modulating", image: "/images/products/sm/sm-1700sm-5000.jpg", summary: "Actuator geared với torque tới 16.950 Nm và modulating duty tới 2.000 starts mỗi giờ.", description: "SM-1700/5000 phù hợp damper, vane, valve và process control cần positioning chính xác.", highlights: ["Torque tới 16.950 Nm", "2.000 starts/giờ", "Automatic torque limiting", "Self-locking drive"], specs: [["Torque", "Tới 16.950 Nm"], ["SM-1700 rotation", "90–120°"], ["SM-5000 rotation", "33–90°"], ["Duty", "2.000 starts/giờ"], ["Nguồn", "1 pha · 3 pha · DC theo model"], ["Override", "Manual tiêu chuẩn"]], officialUrl: "https://www.rotork.com/en/products/precision-modulating-actuators/sm/sm-1700sm-5000" },
  { slug: "sm-6000", name: "SM-6000", type: "Part-turn geared", duty: "Continuous modulation", image: "/images/products/sm/sm-6000.jpg", summary: "Actuator high-torque tới 35.251 Nm, rotation tới 313° và continuous unrestricted modulation.", description: "SM-6000 dành cho process control cần tốc độ cao, torque lớn và positioning chính xác.", highlights: ["Torque tới 35.251 Nm", "Rotation tới 313°", "Continuous modulation", "Fieldbus options"], specs: [["Torque", "Tới 35.251 Nm"], ["Rotation", "Tới 313°"], ["Duty", "Continuous unrestricted modulation"], ["Nguồn", "1 pha hoặc 3 pha"], ["Communication", "HART · PROFIBUS · Foundation Fieldbus"], ["Sealing", "Double O-ring"]], officialUrl: "https://www.rotork.com/en/products/precision-modulating-actuators/sm/sm-6000" },
];

export const skilmaticConfig: RangeConfig = {
  slug: "skilmatic-si", name: "Skilmatic SI", categoryName: hydraulicCategory, categorySlug: hydraulicSlug,
  description: "Actuator electro-hydraulic self-contained kết hợp vận hành điện, điều khiển thủy lực chính xác và spring-return fail-safe cho safety applications.", heroBadge: "Fail-safe\nSIL actuation",
  facts: [["SIL 2 / 3", "Theo system và certification"], ["400 kN", "Linear thrust tới mức công bố"], ["200.000 Nm", "Part-turn torque tới mức công bố"], ["PST / ESD", "Safety test và shutdown options"]],
  overviewTitle: "Fail-safe electro-hydraulic cho safety instrumented systems", overview: ["Skilmatic SI hỗ trợ fail-safe close, open hoặc lock-in-last position, cùng Partial Stroke Testing và ESD/PSD inputs.", "Range có model SI3 tiêu chuẩn, SI4 tùy biến tải lớn và Remote Hand Station cho vị trí khó tiếp cận."],
  selectionTitle: "Chọn chuyển động, fail action và safety architecture", selectionIntro: "Cần xác định linear hoặc part-turn, load, fail position, nguồn, PST/ESD logic, SIL và network protocol.",
  selectionSteps: [["Linear hay part-turn?", "Đối chiếu thrust hoặc torque và hành trình/góc quay."], ["Fail-safe action?", "Xác định fail-close, fail-open hoặc lock-in-last position."], ["Safety và control?", "Xác nhận SIL, PST, ESD/PSD, 4–20 mA, fieldbus và enclosure."]],
  commonFeatures: [["Spring-return fail-safe", "Cơ khí đưa actuator về trạng thái an toàn theo cấu hình."], ["PST and ESD", "Partial Stroke Testing và shutdown inputs có thể cấu hình."], ["Data logging", "Ghi tới 3.000 events theo mô tả của model SI."], ["Hazardous-area options", "Enclosure watertight và explosionproof theo chứng nhận."]],
  brochureCode: "PUB021-063", brochureTitle: "Skilmatic SI Range Publication", brochureUrl: "https://media.rotork.com/api/public/content/pub021-063-000516-pdf-rtkimportasset3c6acf.pdf", officialRangeUrl: "https://www.rotork.com/en/products/electro-hydraulic-actuators/skilmatic-si",
};

const siCommon: [string, string][] = [["Nguồn", "1 pha · 3 pha · 24 VDC"], ["Fail action", "Close · Open · Lock-in-last"], ["Control", "4–20 mA · resolution <0,25%"], ["Safety", "Phù hợp system SIL 2/3 theo cấu hình"], ["Events", "Data logger tới 3.000 events"]];
export const skilmaticModels: CatalogModel[] = [
  { slug: "si3-linear", name: "SI3 - Linear", type: "Electro-hydraulic linear", duty: "Fail-safe / SIS", image: "/images/products/skilmatic-si/si3-linear.jpg", summary: "Actuator linear electro-hydraulic tiêu chuẩn với thrust tới 235 kN và spring-return fail-safe.", description: "SI3 Linear kết hợp nguồn điện, hydraulic control, PST, ESD/PSD và network options cho safety applications.", highlights: ["Thrust tới 235 kN", "Spring-return", "PST / ESD", "SIL 2/3 system"], specs: [["Đầu ra", "Linear"], ["Thrust", "Tới 235 kN"], ...siCommon], officialUrl: "https://www.rotork.com/en/products/electro-hydraulic-actuators/skilmatic-si/si3-linear" },
  { slug: "si3-part-turn", name: "SI3 - Part-turn", type: "Electro-hydraulic part-turn", duty: "Fail-safe / SIS", image: "/images/products/skilmatic-si/si3-part-turn.jpg", summary: "Actuator part-turn electro-hydraulic tiêu chuẩn với torque tới 36.000 Nm và spring-return fail-safe.", description: "SI3 Part-turn phục vụ safety applications cần PST, ESD/PSD và fail-safe positioning.", highlights: ["Torque tới 36.000 Nm", "Spring-return", "PST / ESD", "SIL 2/3 system"], specs: [["Đầu ra", "Part-turn"], ["Torque", "Tới 36.000 Nm"], ...siCommon], officialUrl: "https://www.rotork.com/en/products/electro-hydraulic-actuators/skilmatic-si/si3-part-turn" },
  { slug: "si4-linear", name: "SI4 - Linear", type: "Custom electro-hydraulic linear", duty: "Fail-safe / SIS", image: "/images/products/skilmatic-si/si4-linear.jpg", summary: "Actuator linear electro-hydraulic tùy biến cho ứng dụng tới 400 kN, có accumulator option và spring-return fail-safe.", description: "SI4 Linear mở rộng Skilmatic SI cho tải lớn và yêu cầu customization, hỗ trợ multiple backup strokes bằng accumulator tùy chọn.", highlights: ["Thrust tới 400 kN", "Accumulator option", "PST / ESD", "SIL 2/3 system"], specs: [["Đầu ra", "Linear"], ["Thrust", "Tới 400 kN"], ...siCommon], officialUrl: "https://www.rotork.com/en/products/electro-hydraulic-actuators/skilmatic-si/si4-linear" },
  { slug: "si4-part-turn", name: "SI4 - Part-turn", type: "Custom electro-hydraulic part-turn", duty: "Fail-safe / SIS", image: "/images/products/skilmatic-si/si4-part-turn.jpg", summary: "Actuator part-turn electro-hydraulic tùy biến với torque tới 200.000 Nm và spring-return fail-safe.", description: "SI4 Part-turn dành cho torque lớn, có accumulator option, PST, ESD/PSD và network integration.", highlights: ["Torque tới 200.000 Nm", "Accumulator option", "PST / ESD", "SIL 2/3 system"], specs: [["Đầu ra", "Part-turn"], ["Torque", "Tới 200.000 Nm"], ...siCommon], officialUrl: "https://www.rotork.com/en/products/electro-hydraulic-actuators/skilmatic-si/si4-part-turn" },
  { slug: "si3-si4-remote-hand-station-rhs", name: "SI3 SI4 Remote Hand Station (RHS)", type: "Remote interface", duty: "Remote operation", image: "/images/products/skilmatic-si/si3-si4-remote-hand-station-rhs.jpg", summary: "Remote Hand Station sao chép giao diện SI3/SI4 để vận hành, truy vấn và cấu hình từ khoảng cách tới 100 m.", description: "RHS phù hợp khi actuator nằm tại vị trí hazardous hoặc khó tiếp cận, dùng standard data cable và nhận nguồn từ actuator.", highlights: ["Khoảng cách tới 100 m", "Wall / Pole mounting", "IP66/68", "Explosionproof option"], specs: [["Chức năng", "Operation · Interrogation · Configuration"], ["Khoảng cách", "Tới 100 m"], ["Nguồn", "24 VDC từ actuator"], ["Mounting", "Wall hoặc pole"], ["Enclosure", "IP66/68 · 7 m / 72 giờ"], ["Compatibility", "SI3 · SI4"]], officialUrl: "https://www.rotork.com/en/products/electro-hydraulic-actuators/skilmatic-si/si3-si4-remote-hand-station-rhs" },
];

export const modularEHConfig: RangeConfig = {
  slug: "modular-electro-hydraulic", name: "Modular Electro-Hydraulic", categoryName: hydraulicCategory, categorySlug: hydraulicSlug,
  description: "Giải pháp M-EH modular electro-hydraulic cho on/off valve automation, từ basic relay logic đến advanced PLC với diagnostic và SIL-rated ESD.", heroBadge: "Modular hydraulic\nvalve automation",
  facts: [["Basic / Advanced", "Hai cấp độ architecture"], ["≥30 l/min", "Minimum adjustable flowrate"], ["SIL 3", "Advanced safety option"], ["Low power", "Phù hợp infrastructure kể cả solar"]],
  overviewTitle: "Từ on/off cơ bản đến safety logic nâng cao", overview: ["Basic architecture là self-contained relay system tiêu thụ điện thấp, để input signal handling cho end user.", "Advanced architecture sử dụng PLC/EHPC210 và HMI, hỗ trợ network protocol, PST, diagnostics, voting logic và SIL-rated ESD."],
  selectionTitle: "Chọn architecture theo control và safety requirement", selectionIntro: "Cần xác định basic hoặc advanced, flowrate, accumulator, local/remote control, voting logic, PST và SIL.",
  selectionSteps: [["Basic hay Advanced?", "Basic cho on/off đơn giản; Advanced cho PLC, HMI, diagnostics và network."], ["Hydraulic performance?", "Xác định flowrate, stroke time, accumulator và backup pressure."], ["Safety architecture?", "Xác nhận PST, ESD, voting, SIL và line-break functionality."]],
  commonFeatures: [["Modular architecture", "Cấu trúc cơ khí và control có thể cấu hình theo dự án."], ["Low-power operation", "Phù hợp hạ tầng nguồn hạn chế, bao gồm solar theo thiết kế."], ["Advanced diagnostics", "PST, full stroke, solenoid test và accumulator monitoring."], ["Network integration", "Modbus RTU/TCP, PROFIBUS và PROFINET trên advanced system."]],
  brochureCode: "PUB189-001", brochureTitle: "Modular Electro-Hydraulic Brochure", brochureUrl: "https://media.rotork.com/api/public/content/pub189-001-00-0922-pdf-rtkimportasset209c32.pdf", officialRangeUrl: "https://www.rotork.com/en/products/electro-hydraulic-actuators/modular-electro-hydraulic/modular-electro-hydraulic",
};

export const modularEHModel: CatalogModel = { slug: "modular-electro-hydraulic", name: "Modular Electro-Hydraulic", type: "Electro-hydraulic system", duty: "On/off · ESD", image: "/images/products/modular-electro-hydraulic/modular-electro-hydraulic.jpg", summary: "Giải pháp electro-hydraulic modular từ basic on/off đến advanced PLC/HMI với diagnostic và SIL 3 option.", description: "Rotork M-EH cung cấp valve automation robust cho on/off duty, có thể mở rộng flowrate và safety logic theo yêu cầu dự án.", highlights: ["Basic / Advanced architecture", "Flowrate từ 30 l/min", "Optional accumulator", "SIL 3 option"], specs: [["Duty", "On/off · ESD"], ["Minimum flowrate", "30 l/min adjustable"], ["Controller", "Relay logic hoặc PLC/EHPC210"], ["Network", "Modbus · PROFIBUS · PROFINET"], ["Safety", "Tới SIL 3 theo cấu hình"], ["Backup", "Optional accumulator"]], officialUrl: "https://www.rotork.com/en/products/electro-hydraulic-actuators/modular-electro-hydraulic/modular-electro-hydraulic" };

export function findModel(models: CatalogModel[], slug: string) { return models.find((model) => model.slug === slug); }
