import type { CatalogModel, RangeConfig } from "./catalog-types";

export const ckRangeConfig: RangeConfig = {
  slug: "ck-range",
  name: "CK Range",
  categoryName: "Electric Intelligent Actuators",
  categorySlug: "electric-intelligent-actuators",
  description: "Dòng actuator điện modular cho isolation, regulating và modulating duty, có thể lựa chọn external controls, Atronik hoặc Centronik theo mức độ tích hợp của hệ thống.",
  heroBadge: "Modular\nactuation platform",
  facts: [["IP68", "Double-sealed enclosure"], ["6 models", "Isolation và modulating"], ["3 control levels", "External · Atronik · Centronik"], ["Modular", "Lắp đặt và bảo trì linh hoạt"]],
  overviewTitle: "Một nền tảng modular, ba cấp độ điều khiển",
  overview: ["CK Range cho phép cấu hình actuator tiêu chuẩn dùng external controls, Atronik với integral controls cơ bản hoặc Centronik cho tích hợp thông minh và fieldbus.", "Các phiên bản isolation hỗ trợ tới 60 starts mỗi giờ; phiên bản modulating hỗ trợ tới 1.200 starts mỗi giờ. Cấu hình phải được đối chiếu với valve duty và yêu cầu điều khiển thực tế."],
  selectionTitle: "Chọn duty trước, chọn control module sau",
  selectionIntro: "Sáu model được hình thành từ hai duty và ba cấp độ điều khiển. Việc xác định đúng hai yếu tố này giúp thu hẹp cấu hình nhanh chóng.",
  selectionSteps: [["Isolation hay modulating?", "Van on/off ít vận hành hoặc van positioning cần hoạt động thường xuyên."], ["External, Atronik hay Centronik?", "Chọn mức độ integral control, hiển thị, fieldbus và remote mounting cần thiết."], ["Điều kiện lắp đặt?", "Nguồn điện, torque, IP, nhiệt độ, khu vực nguy hiểm và kiểu ghép nối với van."]],
  commonFeatures: [["Thiết kế modular", "Có thể thích ứng nhanh theo site specification và yêu cầu điều khiển."], ["Double-sealed IP68", "Enclosure được thiết kế để tăng khả năng bảo vệ trong môi trường công nghiệp."], ["Plug & socket", "Kết nối hỗ trợ quá trình lắp đặt và bảo trì hiệu quả."], ["Torque protection", "Đo torque và giới hạn torque open/close có thể điều chỉnh độc lập."]],
  brochureCode: "PUB111-103",
  brochureTitle: "CK Range Brochure",
  brochureUrl: "https://media.rotork.com/api/public/content/pub111-103-000217-pdf-rtkimportasset055205.pdf",
  officialRangeUrl: "https://www.rotork.com/en/products/electric-intelligent-actuators/ck-range",
};

export const ckModels: CatalogModel[] = [
  { slug: "ck-standard-isolating-duty", name: "CK - Standard isolating duty", type: "External controls", duty: "Isolation · Class A/B", image: "/images/products/ck-range/ck-standard-isolating-duty.jpg", summary: "Actuator modular cho van on/off ít vận hành, sử dụng external controls và motor switchgear.", description: "CK Standard isolating duty phù hợp shut-off valve và safety valve, hỗ trợ tới 60 starts mỗi giờ và được thiết kế để làm việc với hệ thống điều khiển bên ngoài.", highlights: ["Tối đa 60 starts/giờ", "External controls", "Double-sealed IP68", "Modular design"], specs: [["Nhiệm vụ", "Isolation · Class A/B"], ["Điều khiển", "External controls"], ["Motor switchgear", "External"], ["Tần suất", "Tối đa 60 starts/giờ"], ["Enclosure", "Double-sealed IP68"], ["Ứng dụng", "On/off valves"]], officialUrl: "https://www.rotork.com/en/products/electric-intelligent-actuators/ck-range/ck-standard-isolating-duty" },
  { slug: "cka-atronik-isolating-duty", name: "CKA - Atronik isolating duty", type: "Atronik controls", duty: "Isolation · Class A/B", image: "/images/products/ck-range/cka-atronik-isolating-duty.jpg", summary: "Phiên bản isolation tích hợp Atronik control với cấu hình DIP switch, LED indication và tùy chọn 4–20 mA.", description: "CKA kết hợp CK actuator với Atronik control module cho các yêu cầu integral control tiêu chuẩn, có local selectors, programmable relays và analogue feedback.", highlights: ["Atronik integral controls", "Class A & B", "LED configurable", "Basic network bus"], specs: [["Nhiệm vụ", "Isolation · Class A/B"], ["Control module", "Atronik"], ["Cấu hình", "On-board DIP switches"], ["Analogue option", "4–20 mA input/output"], ["Network", "Basic bus connectivity"], ["Enclosure", "Double-sealed IP68"]], officialUrl: "https://www.rotork.com/en/products/electric-intelligent-actuators/ck-range/cka-atronik-isolating-duty" },
  { slug: "ckc-centronik-isolating-duty", name: "CKC - Centronik isolating duty", type: "Centronik controls", duty: "Isolation · Class A/B", image: "/images/products/ck-range/ckc-centronik-isolating-duty.jpg", summary: "Phiên bản isolation tích hợp Centronik thông minh cho fieldbus, datalogging và remote mounting tới 100 m.", description: "CKC dùng Centronik control module cho hệ thống yêu cầu tích hợp nâng cao, giao diện đa ngôn ngữ và cấu hình không xâm nhập qua local controls, infrared hoặc Bluetooth tùy chọn.", highlights: ["Remote mount tới 100 m", "Fieldbus integration", "Datalogging", "Non-intrusive setting"], specs: [["Nhiệm vụ", "Isolation · Class A/B"], ["Control module", "Centronik"], ["Remote mounting", "Tối đa 100 m"], ["Giao diện", "Multilingual LCD"], ["Kết nối", "Network bus"], ["Enclosure", "Double-sealed IP68"]], officialUrl: "https://www.rotork.com/en/products/electric-intelligent-actuators/ck-range/ckc-centronik-isolating-duty" },
  { slug: "ckr-standard-modulating-duty", name: "CKR - Standard modulating duty", type: "External controls", duty: "Modulating · Class C", image: "/images/products/ck-range/ckr-standard-modulating-duty.jpg", summary: "Actuator modular cho positioning valve vận hành thường xuyên, dùng external controls và tới 1.200 starts mỗi giờ.", description: "CKR Standard modulating duty có drive train tối ưu cho đáp ứng nhanh và được thiết kế cho fine adjustment của process control valve.", highlights: ["Tối đa 1.200 starts/giờ", "External controls", "Fast-response drive train", "Double-sealed IP68"], specs: [["Nhiệm vụ", "Modulating · Class C"], ["Điều khiển", "External controls"], ["Motor switchgear", "External"], ["Tần suất", "Tối đa 1.200 starts/giờ"], ["Enclosure", "Double-sealed IP68"], ["Ứng dụng", "Positioning valves"]], officialUrl: "https://www.rotork.com/en/products/electric-intelligent-actuators/ck-range/ckr-standard-modulating-duty" },
  { slug: "ckra-atronik-modulating-duty", name: "CKRA - Atronik modulating duty", type: "Atronik controls", duty: "Modulating · Class C", image: "/images/products/ck-range/ckra-atronik-modulating-duty.jpg", summary: "Phiên bản modulating Class C với Atronik control, analogue control và integral local selectors.", description: "CKRA dành cho positioning valve hoạt động thường xuyên, kết hợp Atronik controls với programmable relays, analogue feedback và tùy chọn 4–20 mA.", highlights: ["Atronik integral controls", "Class C", "Analogue positioning", "Basic network bus"], specs: [["Nhiệm vụ", "Modulating · Class C"], ["Control module", "Atronik"], ["Cấu hình", "On-board DIP switches"], ["Analogue option", "4–20 mA input/output"], ["Network", "Basic bus connectivity"], ["Enclosure", "Double-sealed IP68"]], officialUrl: "https://www.rotork.com/en/products/electric-intelligent-actuators/ck-range/ckra-atronik-modulating-duty" },
  { slug: "ckrc-centronik-modulating-duty", name: "CKRC - Centronik modulating duty", type: "Centronik controls", duty: "Modulating · Class C", image: "/images/products/ck-range/ckrc-centronik-modulating-duty.jpg", summary: "Phiên bản modulating Class C với Centronik thông minh, fieldbus, datalogging và remote mounting.", description: "CKRC kết hợp modulating actuator với Centronik control module cho hệ thống điều khiển phức tạp, có LCD cấu hình đầy đủ và giám sát vị trí liên tục với DSM.", highlights: ["Centronik intelligent control", "Class C", "Remote mount tới 100 m", "Datalogging & fieldbus"], specs: [["Nhiệm vụ", "Modulating · Class C"], ["Control module", "Centronik"], ["Remote mounting", "Tối đa 100 m"], ["Position monitoring", "DSM option"], ["Kết nối", "Network bus"], ["Enclosure", "Double-sealed IP68"]], officialUrl: "https://www.rotork.com/en/products/electric-intelligent-actuators/ck-range/ckrc-centronik-modulating-duty" },
];

export function getCKModel(slug: string) {
  return ckModels.find((model) => model.slug === slug);
}
